CREATE TABLE IF NOT EXISTS team8_compliance_reports (
    id INT NOT NULL AUTO_INCREMENT,
    report_type VARCHAR(120) NOT NULL,
    department_id INT NULL,
    date_from DATE NOT NULL,
    date_to DATE NOT NULL,
    executive_summary TEXT NOT NULL,
    key_findings LONGTEXT NOT NULL,
    check_details LONGTEXT NOT NULL,
    generated_by INT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'draft',
    approved_by INT NULL,
    approved_at DATETIME NULL,
    document_id INT NULL,
    recipient_emails TEXT NULL,
    email_sent_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_team8_compliance_reports_status (status, created_at),
    KEY idx_team8_compliance_reports_department_dates (department_id, date_from, date_to),
    KEY fk_team8_compliance_reports_generated_by (generated_by),
    KEY fk_team8_compliance_reports_approved_by (approved_by),
    KEY fk_team8_compliance_reports_document (document_id),
    CONSTRAINT fk_team8_compliance_reports_department FOREIGN KEY (department_id) REFERENCES departments(id),
    CONSTRAINT fk_team8_compliance_reports_generated_by FOREIGN KEY (generated_by) REFERENCES users(id),
    CONSTRAINT fk_team8_compliance_reports_approved_by FOREIGN KEY (approved_by) REFERENCES users(id),
    CONSTRAINT fk_team8_compliance_reports_document FOREIGN KEY (document_id) REFERENCES team8_documents(id),
    CONSTRAINT chk_team8_compliance_reports_dates CHECK (date_to >= date_from),
    CONSTRAINT chk_team8_compliance_reports_status CHECK (status IN ('draft', 'approved'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;